baseURL = 'https://julianferrone.com'
languageCode = 'en-us'
title = 'Julian Ferrone'

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML"]
section = ["HTML"]
taxonomy = []      # disables /tags/foo/ etc.
