baseURL = 'https://julianferrone.com'
languageCode = 'en-us'
title = 'Julian Ferrone'
timeZone = 'Australia/Sydney'
enableGitInfo = true

[params]
  [params.author]
    name = "Julian Ferrone" 

[taxonomies]
tag = "tags"
series = "series"

[outputs]
home = ["HTML"]
section = ["HTML"]

[markup]
  [markup.highlight]
    noclasses = false

  [markup.tableOfContents]
    ordered = true

[permalinks]
  [permalinks.page]
    posts = "/:contentbasename"
