baseURL = 'https://julianferrone.com'
languageCode = 'en-us'
title = 'Julian Ferrone'
timeZone = 'Australia/Sydney'
enableGitInfo = true

[params]
  [params.author]
    name = "Julian Ferrone" 

[taxonomies]
tag = "tags"
series = "series"

[outputs]
home = ["HTML"]
section = ["HTML"]
taxonomy = []      # disables /tags/foo/ etc.

[markup]
  [markup.highlight]
    noclasses = false

[permalinks]
  [permalinks.page]
    posts = "/:contentbasename"
